title: Madeline
url: https://jekyllsite-maddiehwray.icom101.repl.co
baseurl: ""
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: Blue 
header: 
  title: Madeline Wray
  tagline: Constantly in motion
  logo_img: images/Calling.png
  logo_img_alt: calling
  background_img: images/header.jpeg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Video
      url: /video
    - label: About
      url: /about
      style: link
  has_social: true
  social_links:
    - label: Email
      url: 'mailto:madelinewray@alum.calarts.edu'
      style: icon
      icon_class: email
      new_window: true
    - label: Facebook
      url: 'https://www.facebook.com/profile.php?id=100010408396060'
      style: icon
      icon_class: facebook      
    - label: Instagram
      url: 'https://www.instagram.com/madelinewrayy/'
      style: icon
      icon_class: instagram
      new_window: true
    # - label: GitHub
    #   url: 'https://github.com/'
    #   style: icon
    #   icon_class: github
    #   new_window: true
footer:
  content: >-
    &copy; 2021 Madeline Wray. All rights reserved. 
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
  #- style-guide.md
